import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const products = [
  {
    slug: 'premium-corporate-tshirt',
    name: 'Premium Corporate T-Shirt',
    category: 'tshirts',
    shortDescription: 'Soft premium cotton t-shirt for branding and events.',
    description:
      'A premium corporate t-shirt designed for bulk orders, events, staff uniforms, and branded campaigns.',
    minOrderQty: 50,
    leadTimeDays: 10,
    material: '100% Cotton',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'White', 'Navy', 'Gray'],
    brandingOptions: ['Screen Printing', 'Embroidery', 'DTF Printing'],
    tags: ['corporate', 'events', 'best-seller'],
    priceTiers: [
      { minQty: 50, maxQty: 149, unitPrice: 36 },
      { minQty: 150, maxQty: 499, unitPrice: 33 },
      { minQty: 500, unitPrice: 30 },
    ],
    image: '/images/products/tshirt.jpg',
    featured: true,
    variants: [
      { sku: 'TS-CORP-BLK-M', variantName: 'Black / M', size: 'M', color: 'Black', unitPrice: '36.00', moq: 50 },
      { sku: 'TS-CORP-WHT-L', variantName: 'White / L', size: 'L', color: 'White', unitPrice: '36.00', moq: 50 },
    ],
  },
  {
    slug: 'custom-event-hoodie',
    name: 'Custom Event Hoodie',
    category: 'hoodies',
    shortDescription: 'Heavyweight hoodie for team wear and corporate campaigns.',
    description:
      'A comfortable hoodie suitable for event teams, internal branding, and premium merchandise.',
    minOrderQty: 30,
    leadTimeDays: 12,
    material: 'Cotton Fleece',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Beige', 'Maroon'],
    brandingOptions: ['Embroidery', 'Screen Printing'],
    tags: ['winter', 'events', 'merch'],
    priceTiers: [
      { minQty: 30, maxQty: 99, unitPrice: 78 },
      { minQty: 100, maxQty: 299, unitPrice: 72 },
      { minQty: 300, unitPrice: 68 },
    ],
    image: '/images/products/hoodie.jpg',
    featured: true,
    variants: [
      { sku: 'HD-EVT-BLK-M', variantName: 'Black / M', size: 'M', color: 'Black', unitPrice: '78.00', moq: 30 },
      { sku: 'HD-EVT-MRN-L', variantName: 'Maroon / L', size: 'L', color: 'Maroon', unitPrice: '78.00', moq: 30 },
    ],
  },
  {
    slug: 'hospitality-staff-uniform',
    name: 'Hospitality Staff Uniform Set',
    category: 'uniforms',
    shortDescription: 'Durable smart-fit uniform set for hotels and restaurants.',
    description:
      'Professional uniform set with breathable fabric and stain-resistant treatment for daily operations.',
    minOrderQty: 40,
    leadTimeDays: 14,
    material: 'Poly-Cotton Blend',
    sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL'],
    colors: ['Charcoal', 'Navy', 'White'],
    brandingOptions: ['Embroidery', 'Woven Patches'],
    tags: ['hospitality', 'uniform', 'staff'],
    priceTiers: [
      { minQty: 40, maxQty: 149, unitPrice: 89 },
      { minQty: 150, maxQty: 399, unitPrice: 83 },
      { minQty: 400, unitPrice: 79 },
    ],
    image: '/images/products/uniform.jpg',
    featured: false,
    variants: [
      { sku: 'UF-HSP-CHR-M', variantName: 'Charcoal / M', size: 'M', color: 'Charcoal', unitPrice: '89.00', moq: 40 },
      { sku: 'UF-HSP-NVY-L', variantName: 'Navy / L', size: 'L', color: 'Navy', unitPrice: '89.00', moq: 40 },
    ],
  },
  {
    slug: 'team-performance-jersey',
    name: 'Team Performance Jersey',
    category: 'jerseys',
    shortDescription: 'Moisture-wicking team jersey with full sublimation support.',
    description:
      'High-performance jersey for sports clubs, school leagues, and corporate tournaments.',
    minOrderQty: 25,
    leadTimeDays: 9,
    material: 'Polyester Mesh',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Custom Palette'],
    brandingOptions: ['Sublimation', 'Heat Transfer'],
    tags: ['sports', 'team', 'custom-colors'],
    priceTiers: [
      { minQty: 25, maxQty: 99, unitPrice: 54 },
      { minQty: 100, maxQty: 249, unitPrice: 49 },
      { minQty: 250, unitPrice: 45 },
    ],
    image: '/images/products/jersey.jpg',
    featured: true,
    variants: [
      { sku: 'JR-PRF-CUS-M', variantName: 'Custom / M', size: 'M', color: 'Custom', unitPrice: '54.00', moq: 25 },
      { sku: 'JR-PRF-CUS-L', variantName: 'Custom / L', size: 'L', color: 'Custom', unitPrice: '54.00', moq: 25 },
    ],
  },
  {
    slug: 'classic-promotional-tshirt',
    name: 'Classic Promotional T-Shirt',
    category: 'tshirts',
    shortDescription: 'Budget-friendly tee for campaigns, expos, and giveaways.',
    description:
      'Lightweight promotional t-shirt built for cost-efficient bulk runs with clean print output.',
    minOrderQty: 100,
    leadTimeDays: 8,
    material: '180 GSM Cotton',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Black', 'Royal Blue', 'Red'],
    brandingOptions: ['Screen Printing', 'Heat Transfer'],
    tags: ['promo', 'budget', 'events'],
    priceTiers: [
      { minQty: 100, maxQty: 299, unitPrice: 22 },
      { minQty: 300, maxQty: 799, unitPrice: 20 },
      { minQty: 800, unitPrice: 18 },
    ],
    image: '/images/products/tshirt-classic.jpg',
    featured: false,
    variants: [
      { sku: 'TS-CLS-WHT-M', variantName: 'White / M', size: 'M', color: 'White', unitPrice: '22.00', moq: 100 },
      { sku: 'TS-CLS-BLK-L', variantName: 'Black / L', size: 'L', color: 'Black', unitPrice: '22.00', moq: 100 },
    ],
  },
  {
    slug: 'premium-long-sleeve-tshirt',
    name: 'Premium Long Sleeve T-Shirt',
    category: 'tshirts',
    shortDescription: 'Long sleeve tee with premium finish for upscale uniforms.',
    description:
      'Designed for premium team uniforms and seasonal campaigns with durable stitching and print-ready surface.',
    minOrderQty: 40,
    leadTimeDays: 11,
    material: 'Combed Cotton',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Navy', 'Olive', 'White'],
    brandingOptions: ['Embroidery', 'Screen Printing', 'DTF Printing'],
    tags: ['premium', 'uniform', 'long-sleeve'],
    priceTiers: [
      { minQty: 40, maxQty: 119, unitPrice: 42 },
      { minQty: 120, maxQty: 349, unitPrice: 39 },
      { minQty: 350, unitPrice: 36 },
    ],
    image: '/images/products/tshirt-longsleeve.jpg',
    featured: true,
    variants: [
      { sku: 'TS-LNG-BLK-M', variantName: 'Black / M', size: 'M', color: 'Black', unitPrice: '42.00', moq: 40 },
      { sku: 'TS-LNG-NVY-L', variantName: 'Navy / L', size: 'L', color: 'Navy', unitPrice: '42.00', moq: 40 },
    ],
  },
  {
    slug: 'zip-up-workwear-hoodie',
    name: 'Zip-Up Workwear Hoodie',
    category: 'hoodies',
    shortDescription: 'Industrial-grade zip hoodie for warehouse and field teams.',
    description:
      'Heavy-duty zip-up hoodie with reinforced seams suitable for long daily shifts and brand customization.',
    minOrderQty: 35,
    leadTimeDays: 13,
    material: 'Brushed Fleece',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Charcoal', 'Black', 'Navy'],
    brandingOptions: ['Embroidery', 'Patch Branding'],
    tags: ['workwear', 'zip', 'durable'],
    priceTiers: [
      { minQty: 35, maxQty: 99, unitPrice: 92 },
      { minQty: 100, maxQty: 249, unitPrice: 86 },
      { minQty: 250, unitPrice: 81 },
    ],
    image: '/images/products/hoodie-zip.jpg',
    featured: false,
    variants: [
      { sku: 'HD-ZIP-CHR-M', variantName: 'Charcoal / M', size: 'M', color: 'Charcoal', unitPrice: '92.00', moq: 35 },
      { sku: 'HD-ZIP-BLK-L', variantName: 'Black / L', size: 'L', color: 'Black', unitPrice: '92.00', moq: 35 },
    ],
  },
  {
    slug: 'lightweight-crew-hoodie',
    name: 'Lightweight Crew Hoodie',
    category: 'hoodies',
    shortDescription: 'Breathable hoodie for event crews and university merch.',
    description:
      'Midweight hoodie balancing comfort and durability for year-round branded apparel programs.',
    minOrderQty: 50,
    leadTimeDays: 10,
    material: 'Cotton-Poly Blend',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Sand', 'Heather Gray', 'Black'],
    brandingOptions: ['Screen Printing', 'Heat Transfer'],
    tags: ['crew', 'merch', 'lightweight'],
    priceTiers: [
      { minQty: 50, maxQty: 149, unitPrice: 64 },
      { minQty: 150, maxQty: 399, unitPrice: 59 },
      { minQty: 400, unitPrice: 55 },
    ],
    image: '/images/products/hoodie-light.jpg',
    featured: true,
    variants: [
      { sku: 'HD-LWT-SND-M', variantName: 'Sand / M', size: 'M', color: 'Sand', unitPrice: '64.00', moq: 50 },
      { sku: 'HD-LWT-HGR-L', variantName: 'Heather Gray / L', size: 'L', color: 'Heather Gray', unitPrice: '64.00', moq: 50 },
    ],
  },
  {
    slug: 'healthcare-scrub-set',
    name: 'Healthcare Scrub Set',
    category: 'uniforms',
    shortDescription: 'Comfort scrub set for hospitals, clinics, and labs.',
    description:
      'Wrinkle-resistant scrub top and pants set with breathable fabric for healthcare operations.',
    minOrderQty: 60,
    leadTimeDays: 16,
    material: 'Poly Rayon Spandex',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Sky Blue', 'Navy', 'Teal'],
    brandingOptions: ['Embroidery', 'Name Patch'],
    tags: ['healthcare', 'scrubs', 'medical'],
    priceTiers: [
      { minQty: 60, maxQty: 179, unitPrice: 96 },
      { minQty: 180, maxQty: 449, unitPrice: 91 },
      { minQty: 450, unitPrice: 86 },
    ],
    image: '/images/products/uniform-scrub.jpg',
    featured: false,
    variants: [
      { sku: 'UF-SCR-SKY-M', variantName: 'Sky Blue / M', size: 'M', color: 'Sky Blue', unitPrice: '96.00', moq: 60 },
      { sku: 'UF-SCR-NVY-L', variantName: 'Navy / L', size: 'L', color: 'Navy', unitPrice: '96.00', moq: 60 },
    ],
  },
  {
    slug: 'industrial-coverall-uniform',
    name: 'Industrial Coverall Uniform',
    category: 'uniforms',
    shortDescription: 'Safety-first coverall for construction and maintenance teams.',
    description:
      'Durable coverall uniform with utility pockets and optional reflective branding placements.',
    minOrderQty: 30,
    leadTimeDays: 18,
    material: 'Heavy Twill',
    sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL'],
    colors: ['Navy', 'Orange', 'Gray'],
    brandingOptions: ['Embroidery', 'Reflective Print'],
    tags: ['industrial', 'safety', 'coverall'],
    priceTiers: [
      { minQty: 30, maxQty: 99, unitPrice: 128 },
      { minQty: 100, maxQty: 249, unitPrice: 121 },
      { minQty: 250, unitPrice: 114 },
    ],
    image: '/images/products/uniform-coverall.jpg',
    featured: true,
    variants: [
      { sku: 'UF-CVR-NVY-M', variantName: 'Navy / M', size: 'M', color: 'Navy', unitPrice: '128.00', moq: 30 },
      { sku: 'UF-CVR-ORG-L', variantName: 'Orange / L', size: 'L', color: 'Orange', unitPrice: '128.00', moq: 30 },
    ],
  },
  {
    slug: 'esports-gaming-jersey',
    name: 'Esports Gaming Jersey',
    category: 'jerseys',
    shortDescription: 'Fully customizable gaming jersey for esports teams.',
    description:
      'Performance-fit jersey optimized for sublimation graphics, sponsor logos, and player numbering.',
    minOrderQty: 20,
    leadTimeDays: 8,
    material: 'Interlock Polyester',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Custom Palette'],
    brandingOptions: ['Sublimation', 'Heat Transfer'],
    tags: ['esports', 'gaming', 'sublimation'],
    priceTiers: [
      { minQty: 20, maxQty: 79, unitPrice: 58 },
      { minQty: 80, maxQty: 199, unitPrice: 53 },
      { minQty: 200, unitPrice: 48 },
    ],
    image: '/images/products/jersey-esports.jpg',
    featured: true,
    variants: [
      { sku: 'JR-ESP-CUS-M', variantName: 'Custom / M', size: 'M', color: 'Custom', unitPrice: '58.00', moq: 20 },
      { sku: 'JR-ESP-CUS-L', variantName: 'Custom / L', size: 'L', color: 'Custom', unitPrice: '58.00', moq: 20 },
    ],
  },
  {
    slug: 'training-mesh-jersey',
    name: 'Training Mesh Jersey',
    category: 'jerseys',
    shortDescription: 'Breathable mesh jersey for clubs and academies.',
    description:
      'Lightweight training jersey for repeated washes and everyday team practice sessions.',
    minOrderQty: 35,
    leadTimeDays: 9,
    material: 'Micro Mesh',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Red', 'Blue', 'Black', 'White'],
    brandingOptions: ['Heat Transfer', 'Screen Printing'],
    tags: ['training', 'sports', 'academy'],
    priceTiers: [
      { minQty: 35, maxQty: 119, unitPrice: 47 },
      { minQty: 120, maxQty: 299, unitPrice: 43 },
      { minQty: 300, unitPrice: 39 },
    ],
    image: '/images/products/jersey-training.jpg',
    featured: false,
    variants: [
      { sku: 'JR-TRN-RED-M', variantName: 'Red / M', size: 'M', color: 'Red', unitPrice: '47.00', moq: 35 },
      { sku: 'JR-TRN-BLU-L', variantName: 'Blue / L', size: 'L', color: 'Blue', unitPrice: '47.00', moq: 35 },
    ],
  },
  {
    slug: 'embroidered-cotton-cap',
    name: 'Embroidered Cotton Cap',
    category: 'caps',
    shortDescription: '6-panel cap with curved brim and premium embroidery finish.',
    description:
      'High-quality cotton caps for retail merch, events, and staff accessories with durable fit.',
    minOrderQty: 100,
    leadTimeDays: 10,
    material: 'Brushed Cotton',
    sizes: ['One Size'],
    colors: ['Black', 'Navy', 'Khaki', 'White'],
    brandingOptions: ['Embroidery', 'Woven Label'],
    tags: ['caps', 'headwear', 'merch'],
    priceTiers: [
      { minQty: 100, maxQty: 299, unitPrice: 21 },
      { minQty: 300, maxQty: 799, unitPrice: 19 },
      { minQty: 800, unitPrice: 17 },
    ],
    image: '/images/products/cap-embroidered.jpg',
    featured: true,
    variants: [
      { sku: 'CP-EMB-BLK-OS', variantName: 'Black / One Size', size: 'One Size', color: 'Black', unitPrice: '21.00', moq: 100 },
      { sku: 'CP-EMB-NVY-OS', variantName: 'Navy / One Size', size: 'One Size', color: 'Navy', unitPrice: '21.00', moq: 100 },
    ],
  },
  {
    slug: 'performance-sports-cap',
    name: 'Performance Sports Cap',
    category: 'caps',
    shortDescription: 'Moisture-wicking cap for sports and outdoor promotions.',
    description:
      'Lightweight sports cap with ventilated side panels and adjustable back strap.',
    minOrderQty: 80,
    leadTimeDays: 9,
    material: 'Quick-Dry Polyester',
    sizes: ['One Size'],
    colors: ['Black', 'Royal Blue', 'Neon Green'],
    brandingOptions: ['Heat Transfer', 'Embroidery'],
    tags: ['sports', 'caps', 'outdoor'],
    priceTiers: [
      { minQty: 80, maxQty: 249, unitPrice: 24 },
      { minQty: 250, maxQty: 599, unitPrice: 22 },
      { minQty: 600, unitPrice: 20 },
    ],
    image: '/images/products/cap-sports.jpg',
    featured: false,
    variants: [
      { sku: 'CP-SPR-BLK-OS', variantName: 'Black / One Size', size: 'One Size', color: 'Black', unitPrice: '24.00', moq: 80 },
      { sku: 'CP-SPR-BLU-OS', variantName: 'Royal Blue / One Size', size: 'One Size', color: 'Royal Blue', unitPrice: '24.00', moq: 80 },
    ],
  },
  {
    slug: 'softshell-corporate-jacket',
    name: 'Softshell Corporate Jacket',
    category: 'jackets',
    shortDescription: 'Wind-resistant softshell jacket for premium team uniforms.',
    description:
      'Professional softshell outerwear ideal for sales teams, field staff, and executive gifting.',
    minOrderQty: 25,
    leadTimeDays: 14,
    material: 'Polyester Softshell',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Navy', 'Gray'],
    brandingOptions: ['Embroidery', 'Patch Branding'],
    tags: ['jacket', 'corporate', 'premium'],
    priceTiers: [
      { minQty: 25, maxQty: 79, unitPrice: 139 },
      { minQty: 80, maxQty: 199, unitPrice: 131 },
      { minQty: 200, unitPrice: 123 },
    ],
    image: '/images/products/jacket-softshell.jpg',
    featured: true,
    variants: [
      { sku: 'JK-SFT-BLK-M', variantName: 'Black / M', size: 'M', color: 'Black', unitPrice: '139.00', moq: 25 },
      { sku: 'JK-SFT-NVY-L', variantName: 'Navy / L', size: 'L', color: 'Navy', unitPrice: '139.00', moq: 25 },
    ],
  },
  {
    slug: 'light-puffer-jacket',
    name: 'Light Puffer Jacket',
    category: 'jackets',
    shortDescription: 'Insulated puffer jacket for winter events and logistics crews.',
    description:
      'Compact insulated jacket delivering warmth with lightweight construction and logo-friendly panels.',
    minOrderQty: 20,
    leadTimeDays: 15,
    material: 'Nylon Shell with Polyfill',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Olive', 'Navy'],
    brandingOptions: ['Embroidery', 'Heat Transfer'],
    tags: ['winter', 'puffer', 'logistics'],
    priceTiers: [
      { minQty: 20, maxQty: 69, unitPrice: 158 },
      { minQty: 70, maxQty: 179, unitPrice: 149 },
      { minQty: 180, unitPrice: 141 },
    ],
    image: '/images/products/jacket-puffer.jpg',
    featured: false,
    variants: [
      { sku: 'JK-PUF-BLK-M', variantName: 'Black / M', size: 'M', color: 'Black', unitPrice: '158.00', moq: 20 },
      { sku: 'JK-PUF-OLV-L', variantName: 'Olive / L', size: 'L', color: 'Olive', unitPrice: '158.00', moq: 20 },
    ],
  },
  {
    slug: 'oversized-streetwear-tee',
    name: 'Oversized Streetwear Tee',
    category: 'tshirts',
    shortDescription: 'Heavyweight oversized fit for premium merch drops.',
    description:
      'Streetwear-inspired oversized t-shirt suitable for modern brand merchandise and creator collections.',
    minOrderQty: 60,
    leadTimeDays: 12,
    material: '240 GSM Cotton',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Bone', 'Sand', 'Olive'],
    brandingOptions: ['Screen Printing', 'DTG', 'Embroidery'],
    tags: ['streetwear', 'oversized', 'merch'],
    priceTiers: [
      { minQty: 60, maxQty: 179, unitPrice: 44 },
      { minQty: 180, maxQty: 449, unitPrice: 40 },
      { minQty: 450, unitPrice: 37 },
    ],
    image: '/images/products/tshirt-oversized.jpg',
    featured: true,
    variants: [
      { sku: 'TS-OVR-BLK-M', variantName: 'Black / M', size: 'M', color: 'Black', unitPrice: '44.00', moq: 60 },
      { sku: 'TS-OVR-BON-L', variantName: 'Bone / L', size: 'L', color: 'Bone', unitPrice: '44.00', moq: 60 },
    ],
  },
  {
    slug: 'polo-corporate-premium',
    name: 'Premium Corporate Polo',
    category: 'tshirts',
    shortDescription: 'Collar polo for executive and front-desk uniforms.',
    description:
      'High-quality polo shirt offering a refined look for premium service teams and branded office wear.',
    minOrderQty: 50,
    leadTimeDays: 11,
    material: 'Pique Cotton Blend',
    sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL'],
    colors: ['White', 'Navy', 'Black', 'Maroon'],
    brandingOptions: ['Embroidery', 'Screen Printing'],
    tags: ['polo', 'corporate', 'uniform'],
    priceTiers: [
      { minQty: 50, maxQty: 149, unitPrice: 48 },
      { minQty: 150, maxQty: 399, unitPrice: 44 },
      { minQty: 400, unitPrice: 41 },
    ],
    image: '/images/products/polo-premium.jpg',
    featured: true,
    variants: [
      { sku: 'PL-PRM-WHT-M', variantName: 'White / M', size: 'M', color: 'White', unitPrice: '48.00', moq: 50 },
      { sku: 'PL-PRM-NVY-L', variantName: 'Navy / L', size: 'L', color: 'Navy', unitPrice: '48.00', moq: 50 },
    ],
  },
  {
    slug: 'french-terry-pullover-hoodie',
    name: 'French Terry Pullover Hoodie',
    category: 'hoodies',
    shortDescription: 'Premium pullover with clean silhouette and soft hand-feel.',
    description:
      'Premium French terry hoodie crafted for retail-quality branding and comfortable all-day wear.',
    minOrderQty: 40,
    leadTimeDays: 12,
    material: 'French Terry Cotton',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Stone', 'Charcoal', 'Navy'],
    brandingOptions: ['Embroidery', 'Puff Print', 'Screen Printing'],
    tags: ['premium', 'hoodie', 'retail'],
    priceTiers: [
      { minQty: 40, maxQty: 119, unitPrice: 88 },
      { minQty: 120, maxQty: 299, unitPrice: 82 },
      { minQty: 300, unitPrice: 76 },
    ],
    image: '/images/products/hoodie-french-terry.jpg',
    featured: true,
    variants: [
      { sku: 'HD-FTY-STN-M', variantName: 'Stone / M', size: 'M', color: 'Stone', unitPrice: '88.00', moq: 40 },
      { sku: 'HD-FTY-CHR-L', variantName: 'Charcoal / L', size: 'L', color: 'Charcoal', unitPrice: '88.00', moq: 40 },
    ],
  },
  {
    slug: 'athleisure-track-hoodie',
    name: 'Athleisure Track Hoodie',
    category: 'hoodies',
    shortDescription: 'Sport-inspired hoodie for clubs and active teams.',
    description:
      'Performance hoodie featuring ergonomic cut and lightweight insulation for sports organizations.',
    minOrderQty: 45,
    leadTimeDays: 11,
    material: 'Poly Spandex Fleece',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Royal Blue', 'Red'],
    brandingOptions: ['Heat Transfer', 'Embroidery'],
    tags: ['athleisure', 'sports', 'teams'],
    priceTiers: [
      { minQty: 45, maxQty: 139, unitPrice: 72 },
      { minQty: 140, maxQty: 349, unitPrice: 67 },
      { minQty: 350, unitPrice: 63 },
    ],
    image: '/images/products/hoodie-track.jpg',
    featured: false,
    variants: [
      { sku: 'HD-ATH-BLK-M', variantName: 'Black / M', size: 'M', color: 'Black', unitPrice: '72.00', moq: 45 },
      { sku: 'HD-ATH-BLU-L', variantName: 'Royal Blue / L', size: 'L', color: 'Royal Blue', unitPrice: '72.00', moq: 45 },
    ],
  },
  {
    slug: 'chef-kitchen-uniform-set',
    name: 'Chef Kitchen Uniform Set',
    category: 'uniforms',
    shortDescription: 'Heat-friendly chef coat and trouser set for food service.',
    description:
      'Functional chef uniform set designed for restaurants and cloud kitchens with durable construction.',
    minOrderQty: 35,
    leadTimeDays: 15,
    material: 'Poly-Cotton Twill',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Black', 'Gray'],
    brandingOptions: ['Embroidery', 'Name Patch'],
    tags: ['chef', 'kitchen', 'hospitality'],
    priceTiers: [
      { minQty: 35, maxQty: 109, unitPrice: 112 },
      { minQty: 110, maxQty: 279, unitPrice: 106 },
      { minQty: 280, unitPrice: 99 },
    ],
    image: '/images/products/uniform-chef.jpg',
    featured: false,
    variants: [
      { sku: 'UF-CHF-WHT-M', variantName: 'White / M', size: 'M', color: 'White', unitPrice: '112.00', moq: 35 },
      { sku: 'UF-CHF-BLK-L', variantName: 'Black / L', size: 'L', color: 'Black', unitPrice: '112.00', moq: 35 },
    ],
  },
  {
    slug: 'security-guard-uniform',
    name: 'Security Guard Uniform',
    category: 'uniforms',
    shortDescription: 'Structured security uniform for facilities and events.',
    description:
      'Professional security uniform package with shirt and trouser suitable for high-visibility operations.',
    minOrderQty: 50,
    leadTimeDays: 14,
    material: 'Poly Viscose',
    sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL'],
    colors: ['Navy', 'White'],
    brandingOptions: ['Embroidery', 'Patch'],
    tags: ['security', 'facility', 'event'],
    priceTiers: [
      { minQty: 50, maxQty: 149, unitPrice: 104 },
      { minQty: 150, maxQty: 399, unitPrice: 98 },
      { minQty: 400, unitPrice: 92 },
    ],
    image: '/images/products/uniform-security.jpg',
    featured: true,
    variants: [
      { sku: 'UF-SEC-NVY-M', variantName: 'Navy / M', size: 'M', color: 'Navy', unitPrice: '104.00', moq: 50 },
      { sku: 'UF-SEC-WHT-L', variantName: 'White / L', size: 'L', color: 'White', unitPrice: '104.00', moq: 50 },
    ],
  },
  {
    slug: 'basketball-team-jersey-pro',
    name: 'Basketball Team Jersey Pro',
    category: 'jerseys',
    shortDescription: 'Pro-cut basketball jersey with number customization.',
    description:
      'High-performance basketball jersey with breathable mesh and robust color retention.',
    minOrderQty: 24,
    leadTimeDays: 10,
    material: 'Double Knit Polyester',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Custom Palette'],
    brandingOptions: ['Sublimation', 'Tackle Twill Numbering'],
    tags: ['basketball', 'pro', 'teamwear'],
    priceTiers: [
      { minQty: 24, maxQty: 89, unitPrice: 62 },
      { minQty: 90, maxQty: 219, unitPrice: 57 },
      { minQty: 220, unitPrice: 52 },
    ],
    image: '/images/products/jersey-basketball.jpg',
    featured: true,
    variants: [
      { sku: 'JR-BSK-CUS-M', variantName: 'Custom / M', size: 'M', color: 'Custom', unitPrice: '62.00', moq: 24 },
      { sku: 'JR-BSK-CUS-L', variantName: 'Custom / L', size: 'L', color: 'Custom', unitPrice: '62.00', moq: 24 },
    ],
  },
  {
    slug: 'football-match-jersey',
    name: 'Football Match Jersey',
    category: 'jerseys',
    shortDescription: 'Match-day jersey for clubs, schools, and leagues.',
    description:
      'Competition-ready football jersey optimized for ventilation and full-brand sublimation.',
    minOrderQty: 30,
    leadTimeDays: 9,
    material: 'Performance Polyester',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Custom Palette'],
    brandingOptions: ['Sublimation', 'Heat Transfer'],
    tags: ['football', 'matchday', 'clubs'],
    priceTiers: [
      { minQty: 30, maxQty: 119, unitPrice: 56 },
      { minQty: 120, maxQty: 299, unitPrice: 51 },
      { minQty: 300, unitPrice: 46 },
    ],
    image: '/images/products/jersey-football.jpg',
    featured: false,
    variants: [
      { sku: 'JR-FTB-CUS-M', variantName: 'Custom / M', size: 'M', color: 'Custom', unitPrice: '56.00', moq: 30 },
      { sku: 'JR-FTB-CUS-L', variantName: 'Custom / L', size: 'L', color: 'Custom', unitPrice: '56.00', moq: 30 },
    ],
  },
  {
    slug: 'snapback-flat-brim-cap',
    name: 'Snapback Flat Brim Cap',
    category: 'caps',
    shortDescription: 'Modern flat-brim cap ideal for lifestyle brands.',
    description:
      'Structured snapback cap with premium front panel suitable for embroidery and 3D logos.',
    minOrderQty: 120,
    leadTimeDays: 11,
    material: 'Acrylic Wool Blend',
    sizes: ['One Size'],
    colors: ['Black', 'Burgundy', 'Navy'],
    brandingOptions: ['Embroidery', 'PVC Patch'],
    tags: ['snapback', 'retail', 'street'],
    priceTiers: [
      { minQty: 120, maxQty: 349, unitPrice: 25 },
      { minQty: 350, maxQty: 899, unitPrice: 23 },
      { minQty: 900, unitPrice: 21 },
    ],
    image: '/images/products/cap-snapback.jpg',
    featured: true,
    variants: [
      { sku: 'CP-SNP-BLK-OS', variantName: 'Black / One Size', size: 'One Size', color: 'Black', unitPrice: '25.00', moq: 120 },
      { sku: 'CP-SNP-BRG-OS', variantName: 'Burgundy / One Size', size: 'One Size', color: 'Burgundy', unitPrice: '25.00', moq: 120 },
    ],
  },
  {
    slug: 'trucker-mesh-cap',
    name: 'Trucker Mesh Cap',
    category: 'caps',
    shortDescription: 'Ventilated trucker cap for outdoor marketing campaigns.',
    description:
      'Classic trucker silhouette with mesh back and structured front for logo applications.',
    minOrderQty: 90,
    leadTimeDays: 9,
    material: 'Cotton Front + Mesh Back',
    sizes: ['One Size'],
    colors: ['Black/White', 'Navy/White', 'Red/White'],
    brandingOptions: ['Screen Printing', 'Embroidery'],
    tags: ['trucker', 'outdoor', 'campaign'],
    priceTiers: [
      { minQty: 90, maxQty: 279, unitPrice: 20 },
      { minQty: 280, maxQty: 699, unitPrice: 18 },
      { minQty: 700, unitPrice: 16 },
    ],
    image: '/images/products/cap-trucker.jpg',
    featured: false,
    variants: [
      { sku: 'CP-TRK-BKW-OS', variantName: 'Black/White / One Size', size: 'One Size', color: 'Black/White', unitPrice: '20.00', moq: 90 },
      { sku: 'CP-TRK-NVW-OS', variantName: 'Navy/White / One Size', size: 'One Size', color: 'Navy/White', unitPrice: '20.00', moq: 90 },
    ],
  },
  {
    slug: 'bombers-team-jacket',
    name: 'Bombers Team Jacket',
    category: 'jackets',
    shortDescription: 'Stylish bomber jacket for clubs and premium teams.',
    description:
      'Modern bomber jacket designed for branded teamwear and high-impact promotional apparel.',
    minOrderQty: 30,
    leadTimeDays: 16,
    material: 'Nylon Satin',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Navy', 'Green'],
    brandingOptions: ['Embroidery', 'Patch Branding', 'Heat Transfer'],
    tags: ['bomber', 'teamwear', 'premium'],
    priceTiers: [
      { minQty: 30, maxQty: 99, unitPrice: 166 },
      { minQty: 100, maxQty: 249, unitPrice: 157 },
      { minQty: 250, unitPrice: 149 },
    ],
    image: '/images/products/jacket-bomber.jpg',
    featured: true,
    variants: [
      { sku: 'JK-BMB-BLK-M', variantName: 'Black / M', size: 'M', color: 'Black', unitPrice: '166.00', moq: 30 },
      { sku: 'JK-BMB-NVY-L', variantName: 'Navy / L', size: 'L', color: 'Navy', unitPrice: '166.00', moq: 30 },
    ],
  },
  {
    slug: 'rainproof-field-jacket',
    name: 'Rainproof Field Jacket',
    category: 'jackets',
    shortDescription: 'Water-resistant jacket for logistics and field operations.',
    description:
      'Technical field jacket offering weather resistance and practical utility for outdoor teams.',
    minOrderQty: 25,
    leadTimeDays: 15,
    material: 'Waterproof Coated Polyester',
    sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL'],
    colors: ['Black', 'Navy', 'Orange'],
    brandingOptions: ['Reflective Print', 'Embroidery'],
    tags: ['rainproof', 'field', 'logistics'],
    priceTiers: [
      { minQty: 25, maxQty: 84, unitPrice: 174 },
      { minQty: 85, maxQty: 219, unitPrice: 165 },
      { minQty: 220, unitPrice: 156 },
    ],
    image: '/images/products/jacket-rainproof.jpg',
    featured: false,
    variants: [
      { sku: 'JK-RNP-BLK-M', variantName: 'Black / M', size: 'M', color: 'Black', unitPrice: '174.00', moq: 25 },
      { sku: 'JK-RNP-ORG-L', variantName: 'Orange / L', size: 'L', color: 'Orange', unitPrice: '174.00', moq: 25 },
    ],
  },
];

async function main() {
  for (const product of products) {
    const saved = await prisma.product.upsert({
      where: { slug: product.slug },
      create: {
        slug: product.slug,
        name: product.name,
        category: product.category,
        shortDescription: product.shortDescription,
        description: product.description,
        minOrderQty: product.minOrderQty,
        leadTimeDays: product.leadTimeDays,
        material: product.material,
        sizes: product.sizes,
        colors: product.colors,
        brandingOptions: product.brandingOptions,
        tags: product.tags,
        priceTiers: product.priceTiers,
        image: product.image,
        featured: product.featured,
      },
      update: {
        name: product.name,
        category: product.category,
        shortDescription: product.shortDescription,
        description: product.description,
        minOrderQty: product.minOrderQty,
        leadTimeDays: product.leadTimeDays,
        material: product.material,
        sizes: product.sizes,
        colors: product.colors,
        brandingOptions: product.brandingOptions,
        tags: product.tags,
        priceTiers: product.priceTiers,
        image: product.image,
        featured: product.featured,
        isActive: true,
      },
    });

    await prisma.productVariant.deleteMany({ where: { productId: saved.id } });

    await prisma.productVariant.createMany({
      data: product.variants.map((variant) => ({
        productId: saved.id,
        sku: variant.sku,
        variantName: variant.variantName,
        size: variant.size,
        color: variant.color,
        unitPrice: variant.unitPrice,
        moq: variant.moq,
      })),
    });
  }

  console.log(`Seeded ${products.length} products.`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
