export const designTokens = {
  brand: {
    productName: 'Dubai Garments Revenue OS',
    fontPrimary: 'Manrope',
    fontMonospace: "'JetBrains Mono', 'SFMono-Regular', Menlo, Consolas, monospace",
  },
  spacing: {
    xxs: '0.125rem',
    xs: '0.25rem',
    sm: '0.5rem',
    md: '0.75rem',
    lg: '1rem',
    xl: '1.5rem',
    '2xl': '2rem',
    '3xl': '3rem',
  },
  radius: {
    xs: '0.375rem',
    sm: '0.5rem',
    md: '0.75rem',
    lg: '1rem',
    card: '1.1rem',
    pill: '9999px',
  },
  shadow: {
    sm: '0 1px 2px rgba(11, 18, 32, 0.08)',
    md: '0 8px 20px -14px rgba(11, 18, 32, 0.24)',
    lg: '0 14px 32px -18px rgba(11, 18, 32, 0.34)',
    card: '0 18px 38px -22px rgba(11, 18, 32, 0.42)',
    focusRing: '0 0 0 3px rgba(var(--brand-rgb), 0.14)',
  },
  border: {
    widthThin: '1px',
    widthThick: '2px',
    colorSubtle: '#d8e2ef',
    colorStrong: '#c3d3e8',
    colorInverse: 'rgba(255, 255, 255, 0.22)',
  },
  colors: {
    brand50: '#edf3ff',
    brand100: '#dbe7ff',
    brand500: '#1f6fff',
    brand600: '#1554d6',
    brand700: '#1d4ed8',
    accent500: '#06b6d4',
    ink900: '#0b1220',
    ink700: '#27364a',
    ink500: '#55657b',
    surface: '#ffffff',
    surfaceSoft: '#f3f7fc',
    border: '#d8e2ef',
    success: '#16a34a',
    warning: '#d97706',
    danger: '#dc2626',
  },
  motion: {
    fastMs: 120,
    standardMs: 180,
    slowMs: 260,
    easeStandard: 'cubic-bezier(0.2, 0.8, 0.2, 1)',
    easeOut: 'cubic-bezier(0.22, 1, 0.36, 1)',
  },
  layout: {
    containerMax: '1120px',
    contentMax: '960px',
    panelMax: '720px',
    sectionY: '2rem',
    gridGap: '1rem',
  },
  typography: {
    familyBase: "'Manrope', 'Instrument Sans', ui-sans-serif, system-ui, sans-serif",
    familyHeading: "'Space Grotesk', 'Manrope', ui-sans-serif, system-ui, sans-serif",
    familyMono: "'JetBrains Mono', 'SFMono-Regular', Menlo, Consolas, monospace",
    display: 'clamp(2.4rem, 5.8vw, 4rem)',
    heroTitle: 'clamp(2rem, 5vw, 3rem)',
    pageTitle: 'clamp(1.35rem, 2vw, 1.9rem)',
    sectionTitle: 'clamp(1.5rem, 2vw, 2rem)',
    titleMd: '1.125rem',
    body: '1rem',
    small: '0.875rem',
    micro: '0.75rem',
    lineHeightTight: '1.2',
    lineHeightBase: '1.5',
    lineHeightRelaxed: '1.65',
    letterSpacingTight: '-0.02em',
    letterSpacingNormal: '0',
    letterSpacingWide: '0.06em',
  },
} as const;

export type DesignTokens = typeof designTokens;

export const tokenGroups = {
  colors: [
    { key: 'brand50', cssVar: '--color-brand-50', value: designTokens.colors.brand50 },
    { key: 'brand100', cssVar: '--color-brand-100', value: designTokens.colors.brand100 },
    { key: 'brand500', cssVar: '--color-brand-500', value: designTokens.colors.brand500 },
    { key: 'brand600', cssVar: '--color-brand-600', value: designTokens.colors.brand600 },
    { key: 'brand700', cssVar: '--color-brand-700', value: designTokens.colors.brand700 },
    { key: 'accent500', cssVar: '--color-accent-500', value: designTokens.colors.accent500 },
    { key: 'ink900', cssVar: '--color-ink-900', value: designTokens.colors.ink900 },
    { key: 'ink700', cssVar: '--color-ink-700', value: designTokens.colors.ink700 },
    { key: 'ink500', cssVar: '--color-ink-500', value: designTokens.colors.ink500 },
    { key: 'surface', cssVar: '--color-surface', value: designTokens.colors.surface },
    { key: 'surfaceSoft', cssVar: '--color-surface-soft', value: designTokens.colors.surfaceSoft },
    { key: 'border', cssVar: '--color-border', value: designTokens.colors.border },
    { key: 'success', cssVar: '--color-success', value: designTokens.colors.success },
    { key: 'warning', cssVar: '--color-warning', value: designTokens.colors.warning },
    { key: 'danger', cssVar: '--color-danger', value: designTokens.colors.danger },
  ],
  spacing: [
    { key: 'xxs', cssVar: '--space-xxs', value: designTokens.spacing.xxs },
    { key: 'xs', cssVar: '--space-xs', value: designTokens.spacing.xs },
    { key: 'sm', cssVar: '--space-sm', value: designTokens.spacing.sm },
    { key: 'md', cssVar: '--space-md', value: designTokens.spacing.md },
    { key: 'lg', cssVar: '--space-lg', value: designTokens.spacing.lg },
    { key: 'xl', cssVar: '--space-xl', value: designTokens.spacing.xl },
    { key: '2xl', cssVar: '--space-2xl', value: designTokens.spacing['2xl'] },
    { key: '3xl', cssVar: '--space-3xl', value: designTokens.spacing['3xl'] },
  ],
  radius: [
    { key: 'xs', cssVar: '--radius-xs', value: designTokens.radius.xs },
    { key: 'sm', cssVar: '--radius-sm', value: designTokens.radius.sm },
    { key: 'md', cssVar: '--radius-md', value: designTokens.radius.md },
    { key: 'lg', cssVar: '--radius-lg', value: designTokens.radius.lg },
    { key: 'card', cssVar: '--radius-card', value: designTokens.radius.card },
    { key: 'pill', cssVar: '--radius-pill', value: designTokens.radius.pill },
  ],
  shadows: [
    { key: 'sm', cssVar: '--shadow-sm', value: designTokens.shadow.sm },
    { key: 'md', cssVar: '--shadow-md', value: designTokens.shadow.md },
    { key: 'lg', cssVar: '--shadow-lg', value: designTokens.shadow.lg },
    { key: 'card', cssVar: '--shadow-card', value: designTokens.shadow.card },
    { key: 'focusRing', cssVar: '--shadow-focus-ring', value: designTokens.shadow.focusRing },
  ],
  borders: [
    { key: 'widthThin', cssVar: '--border-width-thin', value: designTokens.border.widthThin },
    { key: 'widthThick', cssVar: '--border-width-thick', value: designTokens.border.widthThick },
    { key: 'colorSubtle', cssVar: '--border-color-subtle', value: designTokens.border.colorSubtle },
    { key: 'colorStrong', cssVar: '--border-color-strong', value: designTokens.border.colorStrong },
    { key: 'colorInverse', cssVar: '--border-color-inverse', value: designTokens.border.colorInverse },
  ],
  typography: [
    { key: 'familyBase', cssVar: '--font-family-base', value: designTokens.typography.familyBase },
    { key: 'familyHeading', cssVar: '--font-family-heading', value: designTokens.typography.familyHeading },
    { key: 'familyMono', cssVar: '--font-family-mono', value: designTokens.typography.familyMono },
    { key: 'display', cssVar: '--font-size-display', value: designTokens.typography.display },
    { key: 'heroTitle', cssVar: '--font-size-hero', value: designTokens.typography.heroTitle },
    { key: 'pageTitle', cssVar: '--font-size-page-title', value: designTokens.typography.pageTitle },
    { key: 'sectionTitle', cssVar: '--font-size-section-title', value: designTokens.typography.sectionTitle },
    { key: 'titleMd', cssVar: '--font-size-title-md', value: designTokens.typography.titleMd },
    { key: 'body', cssVar: '--font-size-body', value: designTokens.typography.body },
    { key: 'small', cssVar: '--font-size-small', value: designTokens.typography.small },
    { key: 'micro', cssVar: '--font-size-micro', value: designTokens.typography.micro },
  ],
  layout: [
    { key: 'containerMax', cssVar: '--layout-container-max', value: designTokens.layout.containerMax },
    { key: 'contentMax', cssVar: '--layout-content-max', value: designTokens.layout.contentMax },
    { key: 'panelMax', cssVar: '--layout-panel-max', value: designTokens.layout.panelMax },
    { key: 'sectionY', cssVar: '--layout-section-y', value: designTokens.layout.sectionY },
    { key: 'gridGap', cssVar: '--layout-grid-gap', value: designTokens.layout.gridGap },
  ],
  motion: [
    { key: 'fast', value: `${designTokens.motion.fastMs}ms` },
    { key: 'standard', value: `${designTokens.motion.standardMs}ms` },
    { key: 'slow', value: `${designTokens.motion.slowMs}ms` },
    { key: 'easeStandard', value: designTokens.motion.easeStandard },
    { key: 'easeOut', value: designTokens.motion.easeOut },
  ],
} as const;
